appveyor.yml:
  delete: true

.gitlab-ci.yml:
  delete: true

.rubocop.yml:
  default_configs:
    RSpec/FilePath:
      Enabled: false

.travis.yml:
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9

Gemfile:
  required:
    ':development':
      - gem: puppet-strings
